{{- if and .Values.cleanup.enabled .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ include "wordpress.fullname" . }}-cleanup
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "wordpress.fullname" . }}-cleanup
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
subjects:
- kind: ServiceAccount
  name: {{ include "wordpress.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: {{ include "wordpress.fullname" . }}-cleanup
  apiGroup: rbac.authorization.k8s.io
{{- end }}