{{/* Validate required values */}}
{{- include "wordpress.validateValues" . }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
  {{- with (include "wordpress.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  wordpress-admin-password: {{ include "wordpress.adminPassword" . | b64enc | quote }}
  wordpress-auth-key: {{ include "wordpress.authKey" . | b64enc | quote }}
  wordpress-secure-auth-key: {{ include "wordpress.secureAuthKey" . | b64enc | quote }}
  wordpress-logged-in-key: {{ include "wordpress.loggedInKey" . | b64enc | quote }}
  wordpress-nonce-key: {{ include "wordpress.nonceKey" . | b64enc | quote }}
  wordpress-auth-salt: {{ include "wordpress.authSalt" . | b64enc | quote }}
  wordpress-secure-auth-salt: {{ include "wordpress.secureAuthSalt" . | b64enc | quote }}
  wordpress-logged-in-salt: {{ include "wordpress.loggedInSalt" . | b64enc | quote }}
  wordpress-nonce-salt: {{ include "wordpress.nonceSalt" . | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.mysql.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
  {{- with (include "wordpress.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  mysql-root-password: {{ include "wordpress.mysql.rootPassword" . | b64enc | quote }}
  mysql-password: {{ include "wordpress.mysql.userPassword" . | b64enc | quote }}
  mysql-database: {{ .Values.mysql.auth.database | b64enc | quote }}
  mysql-username: {{ .Values.mysql.auth.username | b64enc | quote }}